#define __AQUERY_TYPES__ \
    AINT32, AFLOAT, ASTR, ADOUBLE, ALDOUBLE, AINT64, AINT128, \
    AINT16, ADATE, ATIME, AINT8, AUINT32, AUINT64, AUINT128, \
    AUINT16, AUINT8, ABOOL, VECTOR, ATIMESTAMP, ACHAR, ASV, \
    NONE, ERROR
